// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="About Creator Studios"
          descriptions={[
            "Creator Studios is a premier digital agency focused on delivering high-impact, conversion-ready websites. We blend modern aesthetics with technical precision to ensure your business stands out in a crowded market.",
            "Our team takes the time to understand your vision, transforming it into a high-performance digital presence that scales alongside your business goals.",
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
