// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="FREQUENTLY ASKED"
          title="Need answers?"
          description="Quick answers to common questions about our services."
          items={[
            {
              question: "What is the turnaround time?",
              answer: "Turnaround ranges from 2 to 7 days depending on the selected plan.",
            },
            {
              question: "Do you offer post-launch support?",
              answer: "Our Premium plan includes 30 days of dedicated support.",
            },
            {
              question: "Can I upgrade my plan later?",
              answer: "Absolutely! We're here to help you grow whenever you're ready.",
            },
            {
              question: "Do you provide hosting?",
              answer: "Yes, all plans include secure, high-speed cloud hosting.",
            },
            {
              question: "What payment methods do you accept?",
              answer: "We accept all major credit cards, bank transfers, and PayPal.",
            },
          ]}
          textAnimation="fade"
          imageSrc="http://img.b2bpic.net/free-photo/flat-lay-notepad-lamp-workplace-night_169016-17382.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
