// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBorderGlow from '@/components/sections/features/FeaturesBorderGlow';
import { Layout, Search, Shield, Smartphone, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBorderGlow
          tag="WHY CHOOSE US"
          title="Built for growth"
          description="Comprehensive solutions that bridge the gap between design and functionality."
          features={[
            {
              icon: Zap,
              title: "Lightning Fast",
              description: "Optimized performance to keep your users engaged.",
            },
            {
              icon: Shield,
              title: "Secure & Reliable",
              description: "SSL certified and secure hosting for peace of mind.",
            },
            {
              icon: Search,
              title: "Advanced SEO",
              description: "Search engine optimized content to boost visibility.",
            },
            {
              icon: Smartphone,
              title: "Mobile Responsive",
              description: "Flawless experiences across all devices and screen sizes.",
            },
            {
              icon: Layout,
              title: "Custom Design",
              description: "Bespoke UI/UX crafted to reflect your unique brand identity.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
