// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplit from '@/components/sections/hero/HeroSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplit
          tag="CREATIVE DIGITAL SOLUTIONS"
          title="We build brands that convert."
          description="Creator Studios specializes in high-performing, professional web solutions tailored for startups and growing businesses. Let's make your digital first impression count."
          primaryButton={{
            text: "View Pricing",
            href: "#pricing",
          }}
          secondaryButton={{
            text: "Contact Us",
            href: "#contact",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/technology-circle-blue-background-digital-transformation-concept_53876-124682.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
