// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="OUR REACH"
          title="Proven results"
          description="Driving performance with precision."
          metrics={[
            {
              value: "150+",
              description: "Projects Completed",
            },
            {
              value: "98%",
              description: "Client Satisfaction",
            },
            {
              value: "24/7",
              description: "Support Ready",
            },
            {
              value: "50+",
              description: "Global Clients",
            },
            {
              value: "4.9/5",
              description: "Average Rating",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
