// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingSplitCards from '@/components/sections/pricing/PricingSplitCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingSplitCards
          tag="TRANSPARENT PRICING"
          title="Choose your plan"
          description="Select the package that fits your business needs."
          plans={[
            {
              tag: "Basic",
              price: "$399",
              period: "one-time",
              description: "Perfect for new businesses looking for a professional start.",
              primaryButton: {
                text: "Choose Basic",
                href: "https://shopify.com/82072305877/account",
              },
              featuresTitle: "Basic Essentials",
              features: [
                "Up to 3 Pages",
                "Mobile Friendly",
                "Contact Form",
                "Basic SEO",
                "Fast Loading",
              ],
            },
            {
              tag: "Popular",
              price: "$599",
              period: "one-time",
              description: "Everything needed to scale and attract more customers.",
              primaryButton: {
                text: "Choose Starter",
                href: "https://shopify.com/82072305877/account",
              },
              featuresTitle: "Starter Suite",
              features: [
                "Up to 7 Pages",
                "Advanced SEO",
                "Booking System",
                "Image Gallery",
                "Priority Support",
              ],
            },
            {
              tag: "Premium",
              price: "$899",
              period: "one-time",
              description: "Comprehensive features for high-performing brands.",
              primaryButton: {
                text: "Choose Premium",
                href: "https://shopify.com/82072305877/account",
              },
              featuresTitle: "Premium Power",
              features: [
                "Up to 12 Pages",
                "Custom Animations",
                "E-commerce Ready",
                "Blog Setup",
                "30 Days Support",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
