/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import React from "react";
import { Check } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ScrollReveal from "@/components/ui/ScrollReveal";

const plans = [
  {
    tag: "Basic",
    price: "$499",
    period: "",
    description: "All sales are final after sale.",
    primaryButton: {
      text: "Choose Basic",
      href: "#"
    },
    featuresTitle: "Basic Features",
    features: [
      "Core features",
      "Standard support"
    ]
  },
  {
    tag: "Starter",
    price: "$699",
    period: "",
    description: "Perfect for growing businesses.",
    primaryButton: {
      text: "Choose Starter",
      href: "#"
    },
    featuresTitle: "Starter Features",
    features: [
      "Core features",
      "Standard support",
      "Advanced analytics"
    ]
  },
  {
    tag: "Premium",
    price: "$899",
    period: "",
    description: "Our most popular comprehensive plan.",
    primaryButton: {
      text: "Choose Premium",
      href: "#"
    },
    featuresTitle: "Premium Features",
    features: [
      "All Starter features",
      "Priority support",
      "Custom integrations"
    ]
  },
  {
    tag: "White",
    price: "$99",
    period: "/month",
    description: "Includes security backups and small edits.",
    primaryButton: {
      text: "Choose White",
      href: "https://creator-studios-2963.myshopify.com/products/standard?pr_prod_strat=collection_fallback&pr_rec_id=5fb631241&pr_rec_pid=9496676761813&pr_ref_pid=9496710774997&pr_seq=uniform"
    },
    featuresTitle: "White Essentials",
    features: [
      "Security backups",
      "Small edits"
    ]
  },
  {
    tag: "Grey",
    price: "$199",
    period: "/month",
    description: "Everything in basic plus up to 2 hours of content changes.",
    primaryButton: {
      text: "Choose Grey",
      href: "https://creator-studios-2963.myshopify.com/products/popular?pr_prod_strat=collection_fallback&pr_rec_id=c2c2faced&pr_rec_pid=9496710774997&pr_ref_pid=9496676761813&pr_seq=uniform"
    },
    featuresTitle: "Grey Suite",
    features: [
      "Security backups",
      "Small edits",
      "Up to 2 hours of content changes"
    ]
  },
  {
    tag: "Premium",
    price: "$399",
    period: "/month",
    description: "Priority support, unlimited small edits, SEO impairments analytics report and more.",
    primaryButton: {
      text: "Choose Premium",
      href: "https://creator-studios-2963.myshopify.com/products/premium-1?pr_prod_strat=collection_fallback&pr_rec_id=c2c2faced&pr_rec_pid=9496710807765&pr_ref_pid=9496676761813&pr_seq=uniform"
    },
    featuresTitle: "Premium Power",
    features: [
      "Priority support",
      "Unlimited small edits",
      "SEO impairments analytics report",
      "And more"
    ]
  }
];

type PricingPlan = {
  tag: string;
  price: string;
  period: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  featuresTitle: string;
  features: string[];
};

const PricingInline = () => (
  <section aria-label="Pricing section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"TRANSPARENT PRICING"}</p>
        </div>

        <TextAnimation
          text={"Choose your plan"}
          variant={"slide-up"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"Select the package that fits your business needs."}
          variant={"slide-up"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
          </div>
        )}
      </div>

      <div className="flex flex-col gap-5 w-content-width mx-auto">
        {plans.map((plan) => (
          <ScrollReveal
            variant="slide-up"
            key={plan.tag}
            className="relative flex flex-col md:flex-row gap-5 md:gap-12 p-5 md:p-12 card rounded"
          >
            {plan.tag === "Starter" && (
              <div className="absolute top-4 right-4 md:top-8 md:right-8 px-3 py-1 text-xs md:text-sm font-medium primary-button rounded">
                Most Popular
              </div>
            )}
            <div className="flex flex-col gap-2 justify-between w-full md:w-1/2">
              <div className="flex flex-col gap-2">
                <div className="px-3 py-1 mb-2 w-fit text-sm card rounded">
                  <p>{plan.tag}</p>
                </div>
                <div className="flex items-baseline gap-1">
                  <span className="text-5xl md:text-6xl font-semibold">{plan.price}</span>
                  <span className="text-2xl font-medium">{plan.period}</span>
                </div>
                <p className="text-xl md:text-2xl leading-snug text-balance">{plan.description}</p>
              </div>

              <div className="flex flex-col gap-3">
                <Button text={plan.primaryButton.text} href={plan.primaryButton.href} variant="primary" className="w-full" />
                {plan.secondaryButton && <Button text={plan.secondaryButton.text} href={plan.secondaryButton.href} variant="secondary" className="w-full" />}
              </div>
            </div>

            <div className="w-full h-px bg-foreground/20 md:hidden" />

            <div className="flex flex-col gap-3 w-full md:w-1/2">
              <h3 className="text-xl font-medium truncate">{plan.featuresTitle}</h3>
              <div className="w-full h-px bg-foreground/5" />
              {plan.features.map((feature) => (
                <div key={feature} className="flex items-start gap-3">
                  <div className="flex items-center justify-center shrink-0 size-6 primary-button rounded">
                    <Check className="size-3 text-primary-cta-text" strokeWidth={2} />
                  </div>
                  <span className="text-base leading-snug">{feature}</span>
                </div>
              ))}
            </div>
          </ScrollReveal>
        ))}
      </div>
    </div>
  </section>
);

export default function PricingSection() {
  return (
    <div data-webild-section="pricing" data-section="pricing" id="pricing">
      <PricingInline />
    </div>
  );
}
