// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="TESTIMONIALS"
          title="Trusted by creators"
          description="Hear what our clients say about us."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Startup Founder",
              quote: "Incredible work on our new site. Fast, professional, and looks great.",
              imageSrc: "http://img.b2bpic.net/free-photo/concentrated-young-businessman-walking-near-business-center_171337-19782.jpg",
            },
            {
              name: "Michael R.",
              role: "Small Business Owner",
              quote: "The Starter plan was a game-changer for our lead generation.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-young-pretty-positive-girl-smiling_176420-9609.jpg",
            },
            {
              name: "Emily C.",
              role: "Creative Professional",
              quote: "Creator Studios exceeded all our expectations for design and functionality.",
              imageSrc: "http://img.b2bpic.net/free-photo/bearded-man-brown-suit-wearing-glasses-looking-with-smile-happy-face_141793-111811.jpg",
            },
            {
              name: "David W.",
              role: "Entrepreneur",
              quote: "The Premium package is well worth the investment. Scaling made easy.",
              imageSrc: "http://img.b2bpic.net/free-photo/business-man-banner-concept-with-copy-space_23-2149601461.jpg",
            },
            {
              name: "Jessica L.",
              role: "Marketing Lead",
              quote: "Smooth process and amazing end result. Highly recommended.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-young-businesswoman-pointing-finger-increasing-graph-transparent-glass_23-2147857306.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
